[package]
name = "bolt-attribute-bolt-component"
version = "0.0.1"
edition = "2021"
description = "Bolt attribute-bolt-component"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
bolt-utils = { path = "../../utils", version = "0.0.1" }
quote = "1.0"
proc-macro2 = "1.0"